@startuml
title "Iteraciones calculo del costo de combustion"
Salamandra -> Salamandra++: calcularCostoCombustionTotal()
loop Para cada madera
    Salamandra -> Madera: calcularCostoCombustion()
    Madera --> Salamandra: costo: int
end
@enduml